<?php
/**
 * Organization
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ContentService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Organization Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Organization implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Organization';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'legal_name' => 'string',
        'business_name' => 'string',
        'slogan' => 'string',
        'homepage' => 'string',
        'facebook_page_username' => 'string',
        'instagram_username' => 'string',
        'linked_in_username' => 'string',
        'twitter_handler' => 'string',
        'git_hub_username' => 'string',
        'contact_points' => '\OpenAPI\Client\Model\ContactPoint[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'legal_name' => null,
        'business_name' => null,
        'slogan' => null,
        'homepage' => null,
        'facebook_page_username' => null,
        'instagram_username' => null,
        'linked_in_username' => null,
        'twitter_handler' => null,
        'git_hub_username' => null,
        'contact_points' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'legal_name' => true,
        'business_name' => true,
        'slogan' => true,
        'homepage' => true,
        'facebook_page_username' => true,
        'instagram_username' => true,
        'linked_in_username' => true,
        'twitter_handler' => true,
        'git_hub_username' => true,
        'contact_points' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'legal_name' => 'legalName',
        'business_name' => 'businessName',
        'slogan' => 'slogan',
        'homepage' => 'homepage',
        'facebook_page_username' => 'facebookPageUsername',
        'instagram_username' => 'instagramUsername',
        'linked_in_username' => 'linkedInUsername',
        'twitter_handler' => 'twitterHandler',
        'git_hub_username' => 'gitHubUsername',
        'contact_points' => 'contactPoints'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'legal_name' => 'setLegalName',
        'business_name' => 'setBusinessName',
        'slogan' => 'setSlogan',
        'homepage' => 'setHomepage',
        'facebook_page_username' => 'setFacebookPageUsername',
        'instagram_username' => 'setInstagramUsername',
        'linked_in_username' => 'setLinkedInUsername',
        'twitter_handler' => 'setTwitterHandler',
        'git_hub_username' => 'setGitHubUsername',
        'contact_points' => 'setContactPoints'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'legal_name' => 'getLegalName',
        'business_name' => 'getBusinessName',
        'slogan' => 'getSlogan',
        'homepage' => 'getHomepage',
        'facebook_page_username' => 'getFacebookPageUsername',
        'instagram_username' => 'getInstagramUsername',
        'linked_in_username' => 'getLinkedInUsername',
        'twitter_handler' => 'getTwitterHandler',
        'git_hub_username' => 'getGitHubUsername',
        'contact_points' => 'getContactPoints'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('legal_name', $data ?? [], null);
        $this->setIfExists('business_name', $data ?? [], null);
        $this->setIfExists('slogan', $data ?? [], null);
        $this->setIfExists('homepage', $data ?? [], null);
        $this->setIfExists('facebook_page_username', $data ?? [], null);
        $this->setIfExists('instagram_username', $data ?? [], null);
        $this->setIfExists('linked_in_username', $data ?? [], null);
        $this->setIfExists('twitter_handler', $data ?? [], null);
        $this->setIfExists('git_hub_username', $data ?? [], null);
        $this->setIfExists('contact_points', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets legal_name
     *
     * @return string|null
     */
    public function getLegalName()
    {
        return $this->container['legal_name'];
    }

    /**
     * Sets legal_name
     *
     * @param string|null $legal_name legal_name
     *
     * @return self
     */
    public function setLegalName($legal_name)
    {
        if (is_null($legal_name)) {
            array_push($this->openAPINullablesSetToNull, 'legal_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('legal_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['legal_name'] = $legal_name;

        return $this;
    }

    /**
     * Gets business_name
     *
     * @return string|null
     */
    public function getBusinessName()
    {
        return $this->container['business_name'];
    }

    /**
     * Sets business_name
     *
     * @param string|null $business_name business_name
     *
     * @return self
     */
    public function setBusinessName($business_name)
    {
        if (is_null($business_name)) {
            array_push($this->openAPINullablesSetToNull, 'business_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('business_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['business_name'] = $business_name;

        return $this;
    }

    /**
     * Gets slogan
     *
     * @return string|null
     */
    public function getSlogan()
    {
        return $this->container['slogan'];
    }

    /**
     * Sets slogan
     *
     * @param string|null $slogan slogan
     *
     * @return self
     */
    public function setSlogan($slogan)
    {
        if (is_null($slogan)) {
            array_push($this->openAPINullablesSetToNull, 'slogan');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('slogan', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['slogan'] = $slogan;

        return $this;
    }

    /**
     * Gets homepage
     *
     * @return string|null
     */
    public function getHomepage()
    {
        return $this->container['homepage'];
    }

    /**
     * Sets homepage
     *
     * @param string|null $homepage homepage
     *
     * @return self
     */
    public function setHomepage($homepage)
    {
        if (is_null($homepage)) {
            array_push($this->openAPINullablesSetToNull, 'homepage');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('homepage', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['homepage'] = $homepage;

        return $this;
    }

    /**
     * Gets facebook_page_username
     *
     * @return string|null
     */
    public function getFacebookPageUsername()
    {
        return $this->container['facebook_page_username'];
    }

    /**
     * Sets facebook_page_username
     *
     * @param string|null $facebook_page_username facebook_page_username
     *
     * @return self
     */
    public function setFacebookPageUsername($facebook_page_username)
    {
        if (is_null($facebook_page_username)) {
            array_push($this->openAPINullablesSetToNull, 'facebook_page_username');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('facebook_page_username', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['facebook_page_username'] = $facebook_page_username;

        return $this;
    }

    /**
     * Gets instagram_username
     *
     * @return string|null
     */
    public function getInstagramUsername()
    {
        return $this->container['instagram_username'];
    }

    /**
     * Sets instagram_username
     *
     * @param string|null $instagram_username instagram_username
     *
     * @return self
     */
    public function setInstagramUsername($instagram_username)
    {
        if (is_null($instagram_username)) {
            array_push($this->openAPINullablesSetToNull, 'instagram_username');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('instagram_username', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['instagram_username'] = $instagram_username;

        return $this;
    }

    /**
     * Gets linked_in_username
     *
     * @return string|null
     */
    public function getLinkedInUsername()
    {
        return $this->container['linked_in_username'];
    }

    /**
     * Sets linked_in_username
     *
     * @param string|null $linked_in_username linked_in_username
     *
     * @return self
     */
    public function setLinkedInUsername($linked_in_username)
    {
        if (is_null($linked_in_username)) {
            array_push($this->openAPINullablesSetToNull, 'linked_in_username');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('linked_in_username', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['linked_in_username'] = $linked_in_username;

        return $this;
    }

    /**
     * Gets twitter_handler
     *
     * @return string|null
     */
    public function getTwitterHandler()
    {
        return $this->container['twitter_handler'];
    }

    /**
     * Sets twitter_handler
     *
     * @param string|null $twitter_handler twitter_handler
     *
     * @return self
     */
    public function setTwitterHandler($twitter_handler)
    {
        if (is_null($twitter_handler)) {
            array_push($this->openAPINullablesSetToNull, 'twitter_handler');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('twitter_handler', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['twitter_handler'] = $twitter_handler;

        return $this;
    }

    /**
     * Gets git_hub_username
     *
     * @return string|null
     */
    public function getGitHubUsername()
    {
        return $this->container['git_hub_username'];
    }

    /**
     * Sets git_hub_username
     *
     * @param string|null $git_hub_username git_hub_username
     *
     * @return self
     */
    public function setGitHubUsername($git_hub_username)
    {
        if (is_null($git_hub_username)) {
            array_push($this->openAPINullablesSetToNull, 'git_hub_username');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('git_hub_username', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['git_hub_username'] = $git_hub_username;

        return $this;
    }

    /**
     * Gets contact_points
     *
     * @return \OpenAPI\Client\Model\ContactPoint[]|null
     */
    public function getContactPoints()
    {
        return $this->container['contact_points'];
    }

    /**
     * Sets contact_points
     *
     * @param \OpenAPI\Client\Model\ContactPoint[]|null $contact_points contact_points
     *
     * @return self
     */
    public function setContactPoints($contact_points)
    {
        if (is_null($contact_points)) {
            array_push($this->openAPINullablesSetToNull, 'contact_points');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('contact_points', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['contact_points'] = $contact_points;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


