<?php
/**
 * RadzenEditorApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * StorageService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * RadzenEditorApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RadzenEditorApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'radzenUploadImage' => [
            'multipart/form-data',
        ],
        'radzenUploadImageScoped' => [
            'multipart/form-data',
        ],
        'radzenUploadSingle' => [
            'multipart/form-data',
        ],
        'radzenUploadSingleScoped' => [
            'multipart/form-data',
        ],
        'radzenUploadStream' => [
            'application/json',
        ],
        'radzenUploadStreamScoped' => [
            'application/json',
        ],
        'radzenUploadUserImage' => [
            'multipart/form-data',
        ],
        'radzenUploadUserImageScoped' => [
            'multipart/form-data',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation radzenUploadImage
     *
     * Upload an editor image to tenant storage.
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $visibility visibility (optional)
     * @param  string $social_profile_id social_profile_id (optional)
     * @param  string $purpose purpose (optional)
     * @param  string $api_version api_version (optional)
     * @param  string $x_api_version x_api_version (optional)
     * @param  \SplFileObject $file file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadImage'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function radzenUploadImage($tenant_id, $visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadImage'][0])
    {
        $this->radzenUploadImageWithHttpInfo($tenant_id, $visibility, $social_profile_id, $purpose, $api_version, $x_api_version, $file, $contentType);
    }

    /**
     * Operation radzenUploadImageWithHttpInfo
     *
     * Upload an editor image to tenant storage.
     *
     * @param  string $tenant_id (required)
     * @param  string $visibility (optional)
     * @param  string $social_profile_id (optional)
     * @param  string $purpose (optional)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadImage'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function radzenUploadImageWithHttpInfo($tenant_id, $visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadImage'][0])
    {
        $request = $this->radzenUploadImageRequest($tenant_id, $visibility, $social_profile_id, $purpose, $api_version, $x_api_version, $file, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation radzenUploadImageAsync
     *
     * Upload an editor image to tenant storage.
     *
     * @param  string $tenant_id (required)
     * @param  string $visibility (optional)
     * @param  string $social_profile_id (optional)
     * @param  string $purpose (optional)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadImage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function radzenUploadImageAsync($tenant_id, $visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadImage'][0])
    {
        return $this->radzenUploadImageAsyncWithHttpInfo($tenant_id, $visibility, $social_profile_id, $purpose, $api_version, $x_api_version, $file, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation radzenUploadImageAsyncWithHttpInfo
     *
     * Upload an editor image to tenant storage.
     *
     * @param  string $tenant_id (required)
     * @param  string $visibility (optional)
     * @param  string $social_profile_id (optional)
     * @param  string $purpose (optional)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadImage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function radzenUploadImageAsyncWithHttpInfo($tenant_id, $visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadImage'][0])
    {
        $returnType = '';
        $request = $this->radzenUploadImageRequest($tenant_id, $visibility, $social_profile_id, $purpose, $api_version, $x_api_version, $file, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'radzenUploadImage'
     *
     * @param  string $tenant_id (required)
     * @param  string $visibility (optional)
     * @param  string $social_profile_id (optional)
     * @param  string $purpose (optional)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadImage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function radzenUploadImageRequest($tenant_id, $visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadImage'][0])
    {

        // verify the required parameter 'tenant_id' is set
        if ($tenant_id === null || (is_array($tenant_id) && count($tenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_id when calling radzenUploadImage'
            );
        }








        $resourcePath = '/api/v2/fs/radzen/tenants/{tenantId}/upload/image';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $visibility,
            'visibility', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $social_profile_id,
            'socialProfileId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $purpose,
            'purpose', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $api_version,
            'api-version', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_api_version !== null) {
            $headerParams['x-api-version'] = ObjectSerializer::toHeaderValue($x_api_version);
        }

        // path params
        if ($tenant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenant_id),
                $resourcePath
            );
        }

        // form params
        if ($file !== null) {
            $multipart = true;
            $formParams['file'] = [];
            $paramFiles = is_array($file) ? $file : [$file];
            foreach ($paramFiles as $paramFile) {
                $formParams['file'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation radzenUploadImageScoped
     *
     * Upload an editor image scoped to a record.
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $record_type record_type (required)
     * @param  string $record_id record_id (required)
     * @param  string $visibility visibility (optional)
     * @param  string $social_profile_id social_profile_id (optional)
     * @param  string $purpose purpose (optional)
     * @param  string $api_version api_version (optional)
     * @param  string $x_api_version x_api_version (optional)
     * @param  \SplFileObject $file file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadImageScoped'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function radzenUploadImageScoped($tenant_id, $record_type, $record_id, $visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadImageScoped'][0])
    {
        $this->radzenUploadImageScopedWithHttpInfo($tenant_id, $record_type, $record_id, $visibility, $social_profile_id, $purpose, $api_version, $x_api_version, $file, $contentType);
    }

    /**
     * Operation radzenUploadImageScopedWithHttpInfo
     *
     * Upload an editor image scoped to a record.
     *
     * @param  string $tenant_id (required)
     * @param  string $record_type (required)
     * @param  string $record_id (required)
     * @param  string $visibility (optional)
     * @param  string $social_profile_id (optional)
     * @param  string $purpose (optional)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadImageScoped'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function radzenUploadImageScopedWithHttpInfo($tenant_id, $record_type, $record_id, $visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadImageScoped'][0])
    {
        $request = $this->radzenUploadImageScopedRequest($tenant_id, $record_type, $record_id, $visibility, $social_profile_id, $purpose, $api_version, $x_api_version, $file, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation radzenUploadImageScopedAsync
     *
     * Upload an editor image scoped to a record.
     *
     * @param  string $tenant_id (required)
     * @param  string $record_type (required)
     * @param  string $record_id (required)
     * @param  string $visibility (optional)
     * @param  string $social_profile_id (optional)
     * @param  string $purpose (optional)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadImageScoped'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function radzenUploadImageScopedAsync($tenant_id, $record_type, $record_id, $visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadImageScoped'][0])
    {
        return $this->radzenUploadImageScopedAsyncWithHttpInfo($tenant_id, $record_type, $record_id, $visibility, $social_profile_id, $purpose, $api_version, $x_api_version, $file, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation radzenUploadImageScopedAsyncWithHttpInfo
     *
     * Upload an editor image scoped to a record.
     *
     * @param  string $tenant_id (required)
     * @param  string $record_type (required)
     * @param  string $record_id (required)
     * @param  string $visibility (optional)
     * @param  string $social_profile_id (optional)
     * @param  string $purpose (optional)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadImageScoped'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function radzenUploadImageScopedAsyncWithHttpInfo($tenant_id, $record_type, $record_id, $visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadImageScoped'][0])
    {
        $returnType = '';
        $request = $this->radzenUploadImageScopedRequest($tenant_id, $record_type, $record_id, $visibility, $social_profile_id, $purpose, $api_version, $x_api_version, $file, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'radzenUploadImageScoped'
     *
     * @param  string $tenant_id (required)
     * @param  string $record_type (required)
     * @param  string $record_id (required)
     * @param  string $visibility (optional)
     * @param  string $social_profile_id (optional)
     * @param  string $purpose (optional)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadImageScoped'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function radzenUploadImageScopedRequest($tenant_id, $record_type, $record_id, $visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadImageScoped'][0])
    {

        // verify the required parameter 'tenant_id' is set
        if ($tenant_id === null || (is_array($tenant_id) && count($tenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_id when calling radzenUploadImageScoped'
            );
        }

        // verify the required parameter 'record_type' is set
        if ($record_type === null || (is_array($record_type) && count($record_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $record_type when calling radzenUploadImageScoped'
            );
        }

        // verify the required parameter 'record_id' is set
        if ($record_id === null || (is_array($record_id) && count($record_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $record_id when calling radzenUploadImageScoped'
            );
        }








        $resourcePath = '/api/v2/fs/radzen/tenants/{tenantId}/{recordType}/{recordId}/upload/image';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $visibility,
            'visibility', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $social_profile_id,
            'socialProfileId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $purpose,
            'purpose', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $api_version,
            'api-version', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_api_version !== null) {
            $headerParams['x-api-version'] = ObjectSerializer::toHeaderValue($x_api_version);
        }

        // path params
        if ($tenant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenant_id),
                $resourcePath
            );
        }
        // path params
        if ($record_type !== null) {
            $resourcePath = str_replace(
                '{' . 'recordType' . '}',
                ObjectSerializer::toPathValue($record_type),
                $resourcePath
            );
        }
        // path params
        if ($record_id !== null) {
            $resourcePath = str_replace(
                '{' . 'recordId' . '}',
                ObjectSerializer::toPathValue($record_id),
                $resourcePath
            );
        }

        // form params
        if ($file !== null) {
            $multipart = true;
            $formParams['file'] = [];
            $paramFiles = is_array($file) ? $file : [$file];
            foreach ($paramFiles as $paramFile) {
                $formParams['file'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation radzenUploadSingle
     *
     * Upload a single editor file to tenant storage.
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $api_version api_version (optional)
     * @param  string $x_api_version x_api_version (optional)
     * @param  \SplFileObject $file file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadSingle'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function radzenUploadSingle($tenant_id, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadSingle'][0])
    {
        $this->radzenUploadSingleWithHttpInfo($tenant_id, $api_version, $x_api_version, $file, $contentType);
    }

    /**
     * Operation radzenUploadSingleWithHttpInfo
     *
     * Upload a single editor file to tenant storage.
     *
     * @param  string $tenant_id (required)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadSingle'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function radzenUploadSingleWithHttpInfo($tenant_id, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadSingle'][0])
    {
        $request = $this->radzenUploadSingleRequest($tenant_id, $api_version, $x_api_version, $file, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation radzenUploadSingleAsync
     *
     * Upload a single editor file to tenant storage.
     *
     * @param  string $tenant_id (required)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadSingle'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function radzenUploadSingleAsync($tenant_id, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadSingle'][0])
    {
        return $this->radzenUploadSingleAsyncWithHttpInfo($tenant_id, $api_version, $x_api_version, $file, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation radzenUploadSingleAsyncWithHttpInfo
     *
     * Upload a single editor file to tenant storage.
     *
     * @param  string $tenant_id (required)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadSingle'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function radzenUploadSingleAsyncWithHttpInfo($tenant_id, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadSingle'][0])
    {
        $returnType = '';
        $request = $this->radzenUploadSingleRequest($tenant_id, $api_version, $x_api_version, $file, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'radzenUploadSingle'
     *
     * @param  string $tenant_id (required)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadSingle'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function radzenUploadSingleRequest($tenant_id, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadSingle'][0])
    {

        // verify the required parameter 'tenant_id' is set
        if ($tenant_id === null || (is_array($tenant_id) && count($tenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_id when calling radzenUploadSingle'
            );
        }





        $resourcePath = '/api/v2/fs/radzen/tenants/{tenantId}/upload/single';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $api_version,
            'api-version', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_api_version !== null) {
            $headerParams['x-api-version'] = ObjectSerializer::toHeaderValue($x_api_version);
        }

        // path params
        if ($tenant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenant_id),
                $resourcePath
            );
        }

        // form params
        if ($file !== null) {
            $multipart = true;
            $formParams['file'] = [];
            $paramFiles = is_array($file) ? $file : [$file];
            foreach ($paramFiles as $paramFile) {
                $formParams['file'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation radzenUploadSingleScoped
     *
     * Upload a single editor file scoped to a record.
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $record_type record_type (required)
     * @param  string $record_id record_id (required)
     * @param  string $api_version api_version (optional)
     * @param  string $x_api_version x_api_version (optional)
     * @param  \SplFileObject $file file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadSingleScoped'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function radzenUploadSingleScoped($tenant_id, $record_type, $record_id, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadSingleScoped'][0])
    {
        $this->radzenUploadSingleScopedWithHttpInfo($tenant_id, $record_type, $record_id, $api_version, $x_api_version, $file, $contentType);
    }

    /**
     * Operation radzenUploadSingleScopedWithHttpInfo
     *
     * Upload a single editor file scoped to a record.
     *
     * @param  string $tenant_id (required)
     * @param  string $record_type (required)
     * @param  string $record_id (required)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadSingleScoped'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function radzenUploadSingleScopedWithHttpInfo($tenant_id, $record_type, $record_id, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadSingleScoped'][0])
    {
        $request = $this->radzenUploadSingleScopedRequest($tenant_id, $record_type, $record_id, $api_version, $x_api_version, $file, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation radzenUploadSingleScopedAsync
     *
     * Upload a single editor file scoped to a record.
     *
     * @param  string $tenant_id (required)
     * @param  string $record_type (required)
     * @param  string $record_id (required)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadSingleScoped'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function radzenUploadSingleScopedAsync($tenant_id, $record_type, $record_id, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadSingleScoped'][0])
    {
        return $this->radzenUploadSingleScopedAsyncWithHttpInfo($tenant_id, $record_type, $record_id, $api_version, $x_api_version, $file, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation radzenUploadSingleScopedAsyncWithHttpInfo
     *
     * Upload a single editor file scoped to a record.
     *
     * @param  string $tenant_id (required)
     * @param  string $record_type (required)
     * @param  string $record_id (required)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadSingleScoped'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function radzenUploadSingleScopedAsyncWithHttpInfo($tenant_id, $record_type, $record_id, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadSingleScoped'][0])
    {
        $returnType = '';
        $request = $this->radzenUploadSingleScopedRequest($tenant_id, $record_type, $record_id, $api_version, $x_api_version, $file, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'radzenUploadSingleScoped'
     *
     * @param  string $tenant_id (required)
     * @param  string $record_type (required)
     * @param  string $record_id (required)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadSingleScoped'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function radzenUploadSingleScopedRequest($tenant_id, $record_type, $record_id, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadSingleScoped'][0])
    {

        // verify the required parameter 'tenant_id' is set
        if ($tenant_id === null || (is_array($tenant_id) && count($tenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_id when calling radzenUploadSingleScoped'
            );
        }

        // verify the required parameter 'record_type' is set
        if ($record_type === null || (is_array($record_type) && count($record_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $record_type when calling radzenUploadSingleScoped'
            );
        }

        // verify the required parameter 'record_id' is set
        if ($record_id === null || (is_array($record_id) && count($record_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $record_id when calling radzenUploadSingleScoped'
            );
        }





        $resourcePath = '/api/v2/fs/radzen/tenants/{tenantId}/{recordType}/{recordId}/upload/single';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $api_version,
            'api-version', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_api_version !== null) {
            $headerParams['x-api-version'] = ObjectSerializer::toHeaderValue($x_api_version);
        }

        // path params
        if ($tenant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenant_id),
                $resourcePath
            );
        }
        // path params
        if ($record_type !== null) {
            $resourcePath = str_replace(
                '{' . 'recordType' . '}',
                ObjectSerializer::toPathValue($record_type),
                $resourcePath
            );
        }
        // path params
        if ($record_id !== null) {
            $resourcePath = str_replace(
                '{' . 'recordId' . '}',
                ObjectSerializer::toPathValue($record_id),
                $resourcePath
            );
        }

        // form params
        if ($file !== null) {
            $multipart = true;
            $formParams['file'] = [];
            $paramFiles = is_array($file) ? $file : [$file];
            foreach ($paramFiles as $paramFile) {
                $formParams['file'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation radzenUploadStream
     *
     * Chunked editor upload (not implemented).
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $api_version api_version (optional)
     * @param  string $x_api_version x_api_version (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadStream'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function radzenUploadStream($tenant_id, $api_version = null, $x_api_version = null, string $contentType = self::contentTypes['radzenUploadStream'][0])
    {
        $this->radzenUploadStreamWithHttpInfo($tenant_id, $api_version, $x_api_version, $contentType);
    }

    /**
     * Operation radzenUploadStreamWithHttpInfo
     *
     * Chunked editor upload (not implemented).
     *
     * @param  string $tenant_id (required)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadStream'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function radzenUploadStreamWithHttpInfo($tenant_id, $api_version = null, $x_api_version = null, string $contentType = self::contentTypes['radzenUploadStream'][0])
    {
        $request = $this->radzenUploadStreamRequest($tenant_id, $api_version, $x_api_version, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation radzenUploadStreamAsync
     *
     * Chunked editor upload (not implemented).
     *
     * @param  string $tenant_id (required)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadStream'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function radzenUploadStreamAsync($tenant_id, $api_version = null, $x_api_version = null, string $contentType = self::contentTypes['radzenUploadStream'][0])
    {
        return $this->radzenUploadStreamAsyncWithHttpInfo($tenant_id, $api_version, $x_api_version, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation radzenUploadStreamAsyncWithHttpInfo
     *
     * Chunked editor upload (not implemented).
     *
     * @param  string $tenant_id (required)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadStream'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function radzenUploadStreamAsyncWithHttpInfo($tenant_id, $api_version = null, $x_api_version = null, string $contentType = self::contentTypes['radzenUploadStream'][0])
    {
        $returnType = '';
        $request = $this->radzenUploadStreamRequest($tenant_id, $api_version, $x_api_version, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'radzenUploadStream'
     *
     * @param  string $tenant_id (required)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadStream'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function radzenUploadStreamRequest($tenant_id, $api_version = null, $x_api_version = null, string $contentType = self::contentTypes['radzenUploadStream'][0])
    {

        // verify the required parameter 'tenant_id' is set
        if ($tenant_id === null || (is_array($tenant_id) && count($tenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_id when calling radzenUploadStream'
            );
        }




        $resourcePath = '/api/v2/fs/radzen/tenants/{tenantId}/upload/stream';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $api_version,
            'api-version', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_api_version !== null) {
            $headerParams['x-api-version'] = ObjectSerializer::toHeaderValue($x_api_version);
        }

        // path params
        if ($tenant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenant_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation radzenUploadStreamScoped
     *
     * Chunked editor upload scoped to a record (not implemented).
     *
     * @param  string $tenant_id tenant_id (required)
     * @param  string $record_type record_type (required)
     * @param  string $record_id record_id (required)
     * @param  string $api_version api_version (optional)
     * @param  string $x_api_version x_api_version (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadStreamScoped'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function radzenUploadStreamScoped($tenant_id, $record_type, $record_id, $api_version = null, $x_api_version = null, string $contentType = self::contentTypes['radzenUploadStreamScoped'][0])
    {
        $this->radzenUploadStreamScopedWithHttpInfo($tenant_id, $record_type, $record_id, $api_version, $x_api_version, $contentType);
    }

    /**
     * Operation radzenUploadStreamScopedWithHttpInfo
     *
     * Chunked editor upload scoped to a record (not implemented).
     *
     * @param  string $tenant_id (required)
     * @param  string $record_type (required)
     * @param  string $record_id (required)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadStreamScoped'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function radzenUploadStreamScopedWithHttpInfo($tenant_id, $record_type, $record_id, $api_version = null, $x_api_version = null, string $contentType = self::contentTypes['radzenUploadStreamScoped'][0])
    {
        $request = $this->radzenUploadStreamScopedRequest($tenant_id, $record_type, $record_id, $api_version, $x_api_version, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation radzenUploadStreamScopedAsync
     *
     * Chunked editor upload scoped to a record (not implemented).
     *
     * @param  string $tenant_id (required)
     * @param  string $record_type (required)
     * @param  string $record_id (required)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadStreamScoped'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function radzenUploadStreamScopedAsync($tenant_id, $record_type, $record_id, $api_version = null, $x_api_version = null, string $contentType = self::contentTypes['radzenUploadStreamScoped'][0])
    {
        return $this->radzenUploadStreamScopedAsyncWithHttpInfo($tenant_id, $record_type, $record_id, $api_version, $x_api_version, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation radzenUploadStreamScopedAsyncWithHttpInfo
     *
     * Chunked editor upload scoped to a record (not implemented).
     *
     * @param  string $tenant_id (required)
     * @param  string $record_type (required)
     * @param  string $record_id (required)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadStreamScoped'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function radzenUploadStreamScopedAsyncWithHttpInfo($tenant_id, $record_type, $record_id, $api_version = null, $x_api_version = null, string $contentType = self::contentTypes['radzenUploadStreamScoped'][0])
    {
        $returnType = '';
        $request = $this->radzenUploadStreamScopedRequest($tenant_id, $record_type, $record_id, $api_version, $x_api_version, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'radzenUploadStreamScoped'
     *
     * @param  string $tenant_id (required)
     * @param  string $record_type (required)
     * @param  string $record_id (required)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadStreamScoped'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function radzenUploadStreamScopedRequest($tenant_id, $record_type, $record_id, $api_version = null, $x_api_version = null, string $contentType = self::contentTypes['radzenUploadStreamScoped'][0])
    {

        // verify the required parameter 'tenant_id' is set
        if ($tenant_id === null || (is_array($tenant_id) && count($tenant_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $tenant_id when calling radzenUploadStreamScoped'
            );
        }

        // verify the required parameter 'record_type' is set
        if ($record_type === null || (is_array($record_type) && count($record_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $record_type when calling radzenUploadStreamScoped'
            );
        }

        // verify the required parameter 'record_id' is set
        if ($record_id === null || (is_array($record_id) && count($record_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $record_id when calling radzenUploadStreamScoped'
            );
        }




        $resourcePath = '/api/v2/fs/radzen/tenants/{tenantId}/{recordType}/{recordId}/upload/stream';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $api_version,
            'api-version', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_api_version !== null) {
            $headerParams['x-api-version'] = ObjectSerializer::toHeaderValue($x_api_version);
        }

        // path params
        if ($tenant_id !== null) {
            $resourcePath = str_replace(
                '{' . 'tenantId' . '}',
                ObjectSerializer::toPathValue($tenant_id),
                $resourcePath
            );
        }
        // path params
        if ($record_type !== null) {
            $resourcePath = str_replace(
                '{' . 'recordType' . '}',
                ObjectSerializer::toPathValue($record_type),
                $resourcePath
            );
        }
        // path params
        if ($record_id !== null) {
            $resourcePath = str_replace(
                '{' . 'recordId' . '}',
                ObjectSerializer::toPathValue($record_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation radzenUploadUserImage
     *
     * Upload an editor image to user storage.
     *
     * @param  string $visibility visibility (optional)
     * @param  string $social_profile_id social_profile_id (optional)
     * @param  string $purpose purpose (optional)
     * @param  string $api_version api_version (optional)
     * @param  string $x_api_version x_api_version (optional)
     * @param  \SplFileObject $file file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadUserImage'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function radzenUploadUserImage($visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadUserImage'][0])
    {
        $this->radzenUploadUserImageWithHttpInfo($visibility, $social_profile_id, $purpose, $api_version, $x_api_version, $file, $contentType);
    }

    /**
     * Operation radzenUploadUserImageWithHttpInfo
     *
     * Upload an editor image to user storage.
     *
     * @param  string $visibility (optional)
     * @param  string $social_profile_id (optional)
     * @param  string $purpose (optional)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadUserImage'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function radzenUploadUserImageWithHttpInfo($visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadUserImage'][0])
    {
        $request = $this->radzenUploadUserImageRequest($visibility, $social_profile_id, $purpose, $api_version, $x_api_version, $file, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation radzenUploadUserImageAsync
     *
     * Upload an editor image to user storage.
     *
     * @param  string $visibility (optional)
     * @param  string $social_profile_id (optional)
     * @param  string $purpose (optional)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadUserImage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function radzenUploadUserImageAsync($visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadUserImage'][0])
    {
        return $this->radzenUploadUserImageAsyncWithHttpInfo($visibility, $social_profile_id, $purpose, $api_version, $x_api_version, $file, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation radzenUploadUserImageAsyncWithHttpInfo
     *
     * Upload an editor image to user storage.
     *
     * @param  string $visibility (optional)
     * @param  string $social_profile_id (optional)
     * @param  string $purpose (optional)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadUserImage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function radzenUploadUserImageAsyncWithHttpInfo($visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadUserImage'][0])
    {
        $returnType = '';
        $request = $this->radzenUploadUserImageRequest($visibility, $social_profile_id, $purpose, $api_version, $x_api_version, $file, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'radzenUploadUserImage'
     *
     * @param  string $visibility (optional)
     * @param  string $social_profile_id (optional)
     * @param  string $purpose (optional)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadUserImage'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function radzenUploadUserImageRequest($visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadUserImage'][0])
    {








        $resourcePath = '/api/v2/fs/radzen/users/upload/image';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $visibility,
            'visibility', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $social_profile_id,
            'socialProfileId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $purpose,
            'purpose', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $api_version,
            'api-version', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_api_version !== null) {
            $headerParams['x-api-version'] = ObjectSerializer::toHeaderValue($x_api_version);
        }


        // form params
        if ($file !== null) {
            $multipart = true;
            $formParams['file'] = [];
            $paramFiles = is_array($file) ? $file : [$file];
            foreach ($paramFiles as $paramFile) {
                $formParams['file'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation radzenUploadUserImageScoped
     *
     * Upload a user editor image scoped to a record.
     *
     * @param  string $record_type record_type (required)
     * @param  string $record_id record_id (required)
     * @param  string $visibility visibility (optional)
     * @param  string $social_profile_id social_profile_id (optional)
     * @param  string $purpose purpose (optional)
     * @param  string $api_version api_version (optional)
     * @param  string $x_api_version x_api_version (optional)
     * @param  \SplFileObject $file file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadUserImageScoped'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return void
     */
    public function radzenUploadUserImageScoped($record_type, $record_id, $visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadUserImageScoped'][0])
    {
        $this->radzenUploadUserImageScopedWithHttpInfo($record_type, $record_id, $visibility, $social_profile_id, $purpose, $api_version, $x_api_version, $file, $contentType);
    }

    /**
     * Operation radzenUploadUserImageScopedWithHttpInfo
     *
     * Upload a user editor image scoped to a record.
     *
     * @param  string $record_type (required)
     * @param  string $record_id (required)
     * @param  string $visibility (optional)
     * @param  string $social_profile_id (optional)
     * @param  string $purpose (optional)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadUserImageScoped'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function radzenUploadUserImageScopedWithHttpInfo($record_type, $record_id, $visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadUserImageScoped'][0])
    {
        $request = $this->radzenUploadUserImageScopedRequest($record_type, $record_id, $visibility, $social_profile_id, $purpose, $api_version, $x_api_version, $file, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation radzenUploadUserImageScopedAsync
     *
     * Upload a user editor image scoped to a record.
     *
     * @param  string $record_type (required)
     * @param  string $record_id (required)
     * @param  string $visibility (optional)
     * @param  string $social_profile_id (optional)
     * @param  string $purpose (optional)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadUserImageScoped'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function radzenUploadUserImageScopedAsync($record_type, $record_id, $visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadUserImageScoped'][0])
    {
        return $this->radzenUploadUserImageScopedAsyncWithHttpInfo($record_type, $record_id, $visibility, $social_profile_id, $purpose, $api_version, $x_api_version, $file, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation radzenUploadUserImageScopedAsyncWithHttpInfo
     *
     * Upload a user editor image scoped to a record.
     *
     * @param  string $record_type (required)
     * @param  string $record_id (required)
     * @param  string $visibility (optional)
     * @param  string $social_profile_id (optional)
     * @param  string $purpose (optional)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadUserImageScoped'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function radzenUploadUserImageScopedAsyncWithHttpInfo($record_type, $record_id, $visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadUserImageScoped'][0])
    {
        $returnType = '';
        $request = $this->radzenUploadUserImageScopedRequest($record_type, $record_id, $visibility, $social_profile_id, $purpose, $api_version, $x_api_version, $file, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'radzenUploadUserImageScoped'
     *
     * @param  string $record_type (required)
     * @param  string $record_id (required)
     * @param  string $visibility (optional)
     * @param  string $social_profile_id (optional)
     * @param  string $purpose (optional)
     * @param  string $api_version (optional)
     * @param  string $x_api_version (optional)
     * @param  \SplFileObject $file (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['radzenUploadUserImageScoped'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function radzenUploadUserImageScopedRequest($record_type, $record_id, $visibility = null, $social_profile_id = null, $purpose = null, $api_version = null, $x_api_version = null, $file = null, string $contentType = self::contentTypes['radzenUploadUserImageScoped'][0])
    {

        // verify the required parameter 'record_type' is set
        if ($record_type === null || (is_array($record_type) && count($record_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $record_type when calling radzenUploadUserImageScoped'
            );
        }

        // verify the required parameter 'record_id' is set
        if ($record_id === null || (is_array($record_id) && count($record_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $record_id when calling radzenUploadUserImageScoped'
            );
        }








        $resourcePath = '/api/v2/fs/radzen/users/{recordType}/{recordId}/upload/image';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $visibility,
            'visibility', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $social_profile_id,
            'socialProfileId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $purpose,
            'purpose', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $api_version,
            'api-version', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_api_version !== null) {
            $headerParams['x-api-version'] = ObjectSerializer::toHeaderValue($x_api_version);
        }

        // path params
        if ($record_type !== null) {
            $resourcePath = str_replace(
                '{' . 'recordType' . '}',
                ObjectSerializer::toPathValue($record_type),
                $resourcePath
            );
        }
        // path params
        if ($record_id !== null) {
            $resourcePath = str_replace(
                '{' . 'recordId' . '}',
                ObjectSerializer::toPathValue($record_id),
                $resourcePath
            );
        }

        // form params
        if ($file !== null) {
            $multipart = true;
            $formParams['file'] = [];
            $paramFiles = is_array($file) ? $file : [$file];
            foreach ($paramFiles as $paramFile) {
                $formParams['file'][] = \GuzzleHttp\Psr7\Utils::tryFopen(
                    ObjectSerializer::toFormValue($paramFile),
                    'rb'
                );
            }
        }

        $headers = $this->headerSelector->selectHeaders(
            [],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
