<?php
/**
 * BudgetAccountEntryCreateDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * AccountingService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * BudgetAccountEntryCreateDto Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BudgetAccountEntryCreateDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BudgetAccountEntryCreateDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'timestamp' => '\DateTime',
        'description' => 'string',
        'planned_amount' => 'float',
        'currency_id' => 'string',
        'debit_account_id' => 'string',
        'credit_account_id' => 'string',
        'budget_id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => 'uuid',
        'timestamp' => 'date-time',
        'description' => null,
        'planned_amount' => 'double',
        'currency_id' => null,
        'debit_account_id' => null,
        'credit_account_id' => null,
        'budget_id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'timestamp' => false,
        'description' => false,
        'planned_amount' => false,
        'currency_id' => false,
        'debit_account_id' => false,
        'credit_account_id' => false,
        'budget_id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'timestamp' => 'timestamp',
        'description' => 'description',
        'planned_amount' => 'plannedAmount',
        'currency_id' => 'currencyId',
        'debit_account_id' => 'debitAccountId',
        'credit_account_id' => 'creditAccountId',
        'budget_id' => 'budgetId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'timestamp' => 'setTimestamp',
        'description' => 'setDescription',
        'planned_amount' => 'setPlannedAmount',
        'currency_id' => 'setCurrencyId',
        'debit_account_id' => 'setDebitAccountId',
        'credit_account_id' => 'setCreditAccountId',
        'budget_id' => 'setBudgetId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'timestamp' => 'getTimestamp',
        'description' => 'getDescription',
        'planned_amount' => 'getPlannedAmount',
        'currency_id' => 'getCurrencyId',
        'debit_account_id' => 'getDebitAccountId',
        'credit_account_id' => 'getCreditAccountId',
        'budget_id' => 'getBudgetId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('timestamp', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('planned_amount', $data ?? [], null);
        $this->setIfExists('currency_id', $data ?? [], null);
        $this->setIfExists('debit_account_id', $data ?? [], null);
        $this->setIfExists('credit_account_id', $data ?? [], null);
        $this->setIfExists('budget_id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ((mb_strlen($this->container['description']) > 300)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 300.";
        }

        if ((mb_strlen($this->container['description']) < 1)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['currency_id'] === null) {
            $invalidProperties[] = "'currency_id' can't be null";
        }
        if ((mb_strlen($this->container['currency_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'currency_id', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['debit_account_id'] === null) {
            $invalidProperties[] = "'debit_account_id' can't be null";
        }
        if ((mb_strlen($this->container['debit_account_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'debit_account_id', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['credit_account_id'] === null) {
            $invalidProperties[] = "'credit_account_id' can't be null";
        }
        if ((mb_strlen($this->container['credit_account_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'credit_account_id', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['budget_id'] === null) {
            $invalidProperties[] = "'budget_id' can't be null";
        }
        if ((mb_strlen($this->container['budget_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'budget_id', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets timestamp
     *
     * @return \DateTime|null
     */
    public function getTimestamp()
    {
        return $this->container['timestamp'];
    }

    /**
     * Sets timestamp
     *
     * @param \DateTime|null $timestamp timestamp
     *
     * @return self
     */
    public function setTimestamp($timestamp)
    {
        if (is_null($timestamp)) {
            throw new \InvalidArgumentException('non-nullable timestamp cannot be null');
        }
        $this->container['timestamp'] = $timestamp;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        if ((mb_strlen($description) > 300)) {
            throw new \InvalidArgumentException('invalid length for $description when calling BudgetAccountEntryCreateDto., must be smaller than or equal to 300.');
        }
        if ((mb_strlen($description) < 1)) {
            throw new \InvalidArgumentException('invalid length for $description when calling BudgetAccountEntryCreateDto., must be bigger than or equal to 1.');
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets planned_amount
     *
     * @return float|null
     */
    public function getPlannedAmount()
    {
        return $this->container['planned_amount'];
    }

    /**
     * Sets planned_amount
     *
     * @param float|null $planned_amount planned_amount
     *
     * @return self
     */
    public function setPlannedAmount($planned_amount)
    {
        if (is_null($planned_amount)) {
            throw new \InvalidArgumentException('non-nullable planned_amount cannot be null');
        }
        $this->container['planned_amount'] = $planned_amount;

        return $this;
    }

    /**
     * Gets currency_id
     *
     * @return string
     */
    public function getCurrencyId()
    {
        return $this->container['currency_id'];
    }

    /**
     * Sets currency_id
     *
     * @param string $currency_id currency_id
     *
     * @return self
     */
    public function setCurrencyId($currency_id)
    {
        if (is_null($currency_id)) {
            throw new \InvalidArgumentException('non-nullable currency_id cannot be null');
        }

        if ((mb_strlen($currency_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $currency_id when calling BudgetAccountEntryCreateDto., must be bigger than or equal to 1.');
        }

        $this->container['currency_id'] = $currency_id;

        return $this;
    }

    /**
     * Gets debit_account_id
     *
     * @return string
     */
    public function getDebitAccountId()
    {
        return $this->container['debit_account_id'];
    }

    /**
     * Sets debit_account_id
     *
     * @param string $debit_account_id debit_account_id
     *
     * @return self
     */
    public function setDebitAccountId($debit_account_id)
    {
        if (is_null($debit_account_id)) {
            throw new \InvalidArgumentException('non-nullable debit_account_id cannot be null');
        }

        if ((mb_strlen($debit_account_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $debit_account_id when calling BudgetAccountEntryCreateDto., must be bigger than or equal to 1.');
        }

        $this->container['debit_account_id'] = $debit_account_id;

        return $this;
    }

    /**
     * Gets credit_account_id
     *
     * @return string
     */
    public function getCreditAccountId()
    {
        return $this->container['credit_account_id'];
    }

    /**
     * Sets credit_account_id
     *
     * @param string $credit_account_id credit_account_id
     *
     * @return self
     */
    public function setCreditAccountId($credit_account_id)
    {
        if (is_null($credit_account_id)) {
            throw new \InvalidArgumentException('non-nullable credit_account_id cannot be null');
        }

        if ((mb_strlen($credit_account_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $credit_account_id when calling BudgetAccountEntryCreateDto., must be bigger than or equal to 1.');
        }

        $this->container['credit_account_id'] = $credit_account_id;

        return $this;
    }

    /**
     * Gets budget_id
     *
     * @return string
     */
    public function getBudgetId()
    {
        return $this->container['budget_id'];
    }

    /**
     * Sets budget_id
     *
     * @param string $budget_id budget_id
     *
     * @return self
     */
    public function setBudgetId($budget_id)
    {
        if (is_null($budget_id)) {
            throw new \InvalidArgumentException('non-nullable budget_id cannot be null');
        }

        if ((mb_strlen($budget_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $budget_id when calling BudgetAccountEntryCreateDto., must be bigger than or equal to 1.');
        }

        $this->container['budget_id'] = $budget_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


