<?php
/**
 * ServiceCaseUpdateDto
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ServicesService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ServiceCaseUpdateDto Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ServiceCaseUpdateDto implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ServiceCaseUpdateDto';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'title' => 'string',
        'description' => 'string',
        'instructions' => 'string',
        'taxable' => 'bool',
        'work_location' => 'string',
        'service_id' => 'string',
        'service_queue_id' => 'string',
        'service_case_type_id' => 'string',
        'service_level_agreement_id' => 'string',
        'individual_id' => 'string',
        'organization_id' => 'string',
        'account_holder_id' => 'string',
        'receiver_business_id' => 'string',
        'currency_id' => 'string',
        'territory_id' => 'string',
        'price_list_id' => 'string',
        'promised_start_date' => '\DateTime',
        'promised_end_date' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'title' => null,
        'description' => null,
        'instructions' => null,
        'taxable' => null,
        'work_location' => null,
        'service_id' => null,
        'service_queue_id' => null,
        'service_case_type_id' => null,
        'service_level_agreement_id' => null,
        'individual_id' => null,
        'organization_id' => null,
        'account_holder_id' => null,
        'receiver_business_id' => null,
        'currency_id' => null,
        'territory_id' => null,
        'price_list_id' => null,
        'promised_start_date' => 'date-time',
        'promised_end_date' => 'date-time'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'title' => true,
        'description' => true,
        'instructions' => true,
        'taxable' => false,
        'work_location' => true,
        'service_id' => true,
        'service_queue_id' => true,
        'service_case_type_id' => true,
        'service_level_agreement_id' => true,
        'individual_id' => true,
        'organization_id' => true,
        'account_holder_id' => true,
        'receiver_business_id' => true,
        'currency_id' => true,
        'territory_id' => true,
        'price_list_id' => true,
        'promised_start_date' => false,
        'promised_end_date' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'title' => 'title',
        'description' => 'description',
        'instructions' => 'instructions',
        'taxable' => 'taxable',
        'work_location' => 'workLocation',
        'service_id' => 'serviceId',
        'service_queue_id' => 'serviceQueueId',
        'service_case_type_id' => 'serviceCaseTypeId',
        'service_level_agreement_id' => 'serviceLevelAgreementId',
        'individual_id' => 'individualId',
        'organization_id' => 'organizationId',
        'account_holder_id' => 'accountHolderId',
        'receiver_business_id' => 'receiverBusinessId',
        'currency_id' => 'currencyId',
        'territory_id' => 'territoryId',
        'price_list_id' => 'priceListId',
        'promised_start_date' => 'promisedStartDate',
        'promised_end_date' => 'promisedEndDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'title' => 'setTitle',
        'description' => 'setDescription',
        'instructions' => 'setInstructions',
        'taxable' => 'setTaxable',
        'work_location' => 'setWorkLocation',
        'service_id' => 'setServiceId',
        'service_queue_id' => 'setServiceQueueId',
        'service_case_type_id' => 'setServiceCaseTypeId',
        'service_level_agreement_id' => 'setServiceLevelAgreementId',
        'individual_id' => 'setIndividualId',
        'organization_id' => 'setOrganizationId',
        'account_holder_id' => 'setAccountHolderId',
        'receiver_business_id' => 'setReceiverBusinessId',
        'currency_id' => 'setCurrencyId',
        'territory_id' => 'setTerritoryId',
        'price_list_id' => 'setPriceListId',
        'promised_start_date' => 'setPromisedStartDate',
        'promised_end_date' => 'setPromisedEndDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'title' => 'getTitle',
        'description' => 'getDescription',
        'instructions' => 'getInstructions',
        'taxable' => 'getTaxable',
        'work_location' => 'getWorkLocation',
        'service_id' => 'getServiceId',
        'service_queue_id' => 'getServiceQueueId',
        'service_case_type_id' => 'getServiceCaseTypeId',
        'service_level_agreement_id' => 'getServiceLevelAgreementId',
        'individual_id' => 'getIndividualId',
        'organization_id' => 'getOrganizationId',
        'account_holder_id' => 'getAccountHolderId',
        'receiver_business_id' => 'getReceiverBusinessId',
        'currency_id' => 'getCurrencyId',
        'territory_id' => 'getTerritoryId',
        'price_list_id' => 'getPriceListId',
        'promised_start_date' => 'getPromisedStartDate',
        'promised_end_date' => 'getPromisedEndDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('title', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('instructions', $data ?? [], null);
        $this->setIfExists('taxable', $data ?? [], null);
        $this->setIfExists('work_location', $data ?? [], null);
        $this->setIfExists('service_id', $data ?? [], null);
        $this->setIfExists('service_queue_id', $data ?? [], null);
        $this->setIfExists('service_case_type_id', $data ?? [], null);
        $this->setIfExists('service_level_agreement_id', $data ?? [], null);
        $this->setIfExists('individual_id', $data ?? [], null);
        $this->setIfExists('organization_id', $data ?? [], null);
        $this->setIfExists('account_holder_id', $data ?? [], null);
        $this->setIfExists('receiver_business_id', $data ?? [], null);
        $this->setIfExists('currency_id', $data ?? [], null);
        $this->setIfExists('territory_id', $data ?? [], null);
        $this->setIfExists('price_list_id', $data ?? [], null);
        $this->setIfExists('promised_start_date', $data ?? [], null);
        $this->setIfExists('promised_end_date', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title title
     *
     * @return self
     */
    public function setTitle($title)
    {
        if (is_null($title)) {
            array_push($this->openAPINullablesSetToNull, 'title');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('title', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets instructions
     *
     * @return string|null
     */
    public function getInstructions()
    {
        return $this->container['instructions'];
    }

    /**
     * Sets instructions
     *
     * @param string|null $instructions instructions
     *
     * @return self
     */
    public function setInstructions($instructions)
    {
        if (is_null($instructions)) {
            array_push($this->openAPINullablesSetToNull, 'instructions');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('instructions', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['instructions'] = $instructions;

        return $this;
    }

    /**
     * Gets taxable
     *
     * @return bool|null
     */
    public function getTaxable()
    {
        return $this->container['taxable'];
    }

    /**
     * Sets taxable
     *
     * @param bool|null $taxable taxable
     *
     * @return self
     */
    public function setTaxable($taxable)
    {
        if (is_null($taxable)) {
            throw new \InvalidArgumentException('non-nullable taxable cannot be null');
        }
        $this->container['taxable'] = $taxable;

        return $this;
    }

    /**
     * Gets work_location
     *
     * @return string|null
     */
    public function getWorkLocation()
    {
        return $this->container['work_location'];
    }

    /**
     * Sets work_location
     *
     * @param string|null $work_location work_location
     *
     * @return self
     */
    public function setWorkLocation($work_location)
    {
        if (is_null($work_location)) {
            array_push($this->openAPINullablesSetToNull, 'work_location');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('work_location', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['work_location'] = $work_location;

        return $this;
    }

    /**
     * Gets service_id
     *
     * @return string|null
     */
    public function getServiceId()
    {
        return $this->container['service_id'];
    }

    /**
     * Sets service_id
     *
     * @param string|null $service_id service_id
     *
     * @return self
     */
    public function setServiceId($service_id)
    {
        if (is_null($service_id)) {
            array_push($this->openAPINullablesSetToNull, 'service_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('service_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['service_id'] = $service_id;

        return $this;
    }

    /**
     * Gets service_queue_id
     *
     * @return string|null
     */
    public function getServiceQueueId()
    {
        return $this->container['service_queue_id'];
    }

    /**
     * Sets service_queue_id
     *
     * @param string|null $service_queue_id service_queue_id
     *
     * @return self
     */
    public function setServiceQueueId($service_queue_id)
    {
        if (is_null($service_queue_id)) {
            array_push($this->openAPINullablesSetToNull, 'service_queue_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('service_queue_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['service_queue_id'] = $service_queue_id;

        return $this;
    }

    /**
     * Gets service_case_type_id
     *
     * @return string|null
     */
    public function getServiceCaseTypeId()
    {
        return $this->container['service_case_type_id'];
    }

    /**
     * Sets service_case_type_id
     *
     * @param string|null $service_case_type_id service_case_type_id
     *
     * @return self
     */
    public function setServiceCaseTypeId($service_case_type_id)
    {
        if (is_null($service_case_type_id)) {
            array_push($this->openAPINullablesSetToNull, 'service_case_type_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('service_case_type_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['service_case_type_id'] = $service_case_type_id;

        return $this;
    }

    /**
     * Gets service_level_agreement_id
     *
     * @return string|null
     */
    public function getServiceLevelAgreementId()
    {
        return $this->container['service_level_agreement_id'];
    }

    /**
     * Sets service_level_agreement_id
     *
     * @param string|null $service_level_agreement_id service_level_agreement_id
     *
     * @return self
     */
    public function setServiceLevelAgreementId($service_level_agreement_id)
    {
        if (is_null($service_level_agreement_id)) {
            array_push($this->openAPINullablesSetToNull, 'service_level_agreement_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('service_level_agreement_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['service_level_agreement_id'] = $service_level_agreement_id;

        return $this;
    }

    /**
     * Gets individual_id
     *
     * @return string|null
     */
    public function getIndividualId()
    {
        return $this->container['individual_id'];
    }

    /**
     * Sets individual_id
     *
     * @param string|null $individual_id individual_id
     *
     * @return self
     */
    public function setIndividualId($individual_id)
    {
        if (is_null($individual_id)) {
            array_push($this->openAPINullablesSetToNull, 'individual_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('individual_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['individual_id'] = $individual_id;

        return $this;
    }

    /**
     * Gets organization_id
     *
     * @return string|null
     */
    public function getOrganizationId()
    {
        return $this->container['organization_id'];
    }

    /**
     * Sets organization_id
     *
     * @param string|null $organization_id organization_id
     *
     * @return self
     */
    public function setOrganizationId($organization_id)
    {
        if (is_null($organization_id)) {
            array_push($this->openAPINullablesSetToNull, 'organization_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('organization_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['organization_id'] = $organization_id;

        return $this;
    }

    /**
     * Gets account_holder_id
     *
     * @return string|null
     */
    public function getAccountHolderId()
    {
        return $this->container['account_holder_id'];
    }

    /**
     * Sets account_holder_id
     *
     * @param string|null $account_holder_id account_holder_id
     *
     * @return self
     */
    public function setAccountHolderId($account_holder_id)
    {
        if (is_null($account_holder_id)) {
            array_push($this->openAPINullablesSetToNull, 'account_holder_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('account_holder_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['account_holder_id'] = $account_holder_id;

        return $this;
    }

    /**
     * Gets receiver_business_id
     *
     * @return string|null
     */
    public function getReceiverBusinessId()
    {
        return $this->container['receiver_business_id'];
    }

    /**
     * Sets receiver_business_id
     *
     * @param string|null $receiver_business_id receiver_business_id
     *
     * @return self
     */
    public function setReceiverBusinessId($receiver_business_id)
    {
        if (is_null($receiver_business_id)) {
            array_push($this->openAPINullablesSetToNull, 'receiver_business_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('receiver_business_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['receiver_business_id'] = $receiver_business_id;

        return $this;
    }

    /**
     * Gets currency_id
     *
     * @return string|null
     */
    public function getCurrencyId()
    {
        return $this->container['currency_id'];
    }

    /**
     * Sets currency_id
     *
     * @param string|null $currency_id currency_id
     *
     * @return self
     */
    public function setCurrencyId($currency_id)
    {
        if (is_null($currency_id)) {
            array_push($this->openAPINullablesSetToNull, 'currency_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('currency_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['currency_id'] = $currency_id;

        return $this;
    }

    /**
     * Gets territory_id
     *
     * @return string|null
     */
    public function getTerritoryId()
    {
        return $this->container['territory_id'];
    }

    /**
     * Sets territory_id
     *
     * @param string|null $territory_id territory_id
     *
     * @return self
     */
    public function setTerritoryId($territory_id)
    {
        if (is_null($territory_id)) {
            array_push($this->openAPINullablesSetToNull, 'territory_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('territory_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['territory_id'] = $territory_id;

        return $this;
    }

    /**
     * Gets price_list_id
     *
     * @return string|null
     */
    public function getPriceListId()
    {
        return $this->container['price_list_id'];
    }

    /**
     * Sets price_list_id
     *
     * @param string|null $price_list_id price_list_id
     *
     * @return self
     */
    public function setPriceListId($price_list_id)
    {
        if (is_null($price_list_id)) {
            array_push($this->openAPINullablesSetToNull, 'price_list_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('price_list_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['price_list_id'] = $price_list_id;

        return $this;
    }

    /**
     * Gets promised_start_date
     *
     * @return \DateTime|null
     */
    public function getPromisedStartDate()
    {
        return $this->container['promised_start_date'];
    }

    /**
     * Sets promised_start_date
     *
     * @param \DateTime|null $promised_start_date promised_start_date
     *
     * @return self
     */
    public function setPromisedStartDate($promised_start_date)
    {
        if (is_null($promised_start_date)) {
            throw new \InvalidArgumentException('non-nullable promised_start_date cannot be null');
        }
        $this->container['promised_start_date'] = $promised_start_date;

        return $this;
    }

    /**
     * Gets promised_end_date
     *
     * @return \DateTime|null
     */
    public function getPromisedEndDate()
    {
        return $this->container['promised_end_date'];
    }

    /**
     * Sets promised_end_date
     *
     * @param \DateTime|null $promised_end_date promised_end_date
     *
     * @return self
     */
    public function setPromisedEndDate($promised_end_date)
    {
        if (is_null($promised_end_date)) {
            throw new \InvalidArgumentException('non-nullable promised_end_date cannot be null');
        }
        $this->container['promised_end_date'] = $promised_end_date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


