<?php
/**
 * DealUnitFlowsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * DealsService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.1.4089
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DealUnitFlowsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DealUnitFlowsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiV2DealsServiceDealUnitFlowsCountGet
     *
     * .
     *
     */
    public function testApiV2DealsServiceDealUnitFlowsCountGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2DealsServiceDealUnitFlowsDealUnitFlowIdDelete
     *
     * .
     *
     */
    public function testApiV2DealsServiceDealUnitFlowsDealUnitFlowIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2DealsServiceDealUnitFlowsDealUnitFlowIdGet
     *
     * .
     *
     */
    public function testApiV2DealsServiceDealUnitFlowsDealUnitFlowIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2DealsServiceDealUnitFlowsDealUnitFlowIdPut
     *
     * .
     *
     */
    public function testApiV2DealsServiceDealUnitFlowsDealUnitFlowIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2DealsServiceDealUnitFlowsDealUnitFlowIdStagesCountGet
     *
     * .
     *
     */
    public function testApiV2DealsServiceDealUnitFlowsDealUnitFlowIdStagesCountGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2DealsServiceDealUnitFlowsDealUnitFlowIdStagesDealUnitFlowStageIdDelete
     *
     * .
     *
     */
    public function testApiV2DealsServiceDealUnitFlowsDealUnitFlowIdStagesDealUnitFlowStageIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2DealsServiceDealUnitFlowsDealUnitFlowIdStagesDealUnitFlowStageIdGet
     *
     * .
     *
     */
    public function testApiV2DealsServiceDealUnitFlowsDealUnitFlowIdStagesDealUnitFlowStageIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2DealsServiceDealUnitFlowsDealUnitFlowIdStagesDealUnitFlowStageIdPut
     *
     * .
     *
     */
    public function testApiV2DealsServiceDealUnitFlowsDealUnitFlowIdStagesDealUnitFlowStageIdPut()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2DealsServiceDealUnitFlowsDealUnitFlowIdStagesGet
     *
     * .
     *
     */
    public function testApiV2DealsServiceDealUnitFlowsDealUnitFlowIdStagesGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2DealsServiceDealUnitFlowsDealUnitFlowIdStagesPost
     *
     * .
     *
     */
    public function testApiV2DealsServiceDealUnitFlowsDealUnitFlowIdStagesPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2DealsServiceDealUnitFlowsGet
     *
     * .
     *
     */
    public function testApiV2DealsServiceDealUnitFlowsGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiV2DealsServiceDealUnitFlowsPost
     *
     * .
     *
     */
    public function testApiV2DealsServiceDealUnitFlowsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
