<?php
/**
 * PoliciesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SupportService
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0.0
 * Contact: support@fenix-alliance.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PoliciesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PoliciesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createRefundPolicyAsync
     *
     * Create a new refund policy.
     *
     */
    public function testCreateRefundPolicyAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createReturnPolicyAsync
     *
     * Create a new return policy.
     *
     */
    public function testCreateReturnPolicyAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createWarrantyPolicyAsync
     *
     * Create a new warranty policy.
     *
     */
    public function testCreateWarrantyPolicyAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteRefundPolicyAsync
     *
     * Delete a refund policy.
     *
     */
    public function testDeleteRefundPolicyAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteReturnPolicyAsync
     *
     * Delete a return policy.
     *
     */
    public function testDeleteReturnPolicyAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteWarrantyPolicyAsync
     *
     * Delete a warranty policy.
     *
     */
    public function testDeleteWarrantyPolicyAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRefundPoliciesAsync
     *
     * Retrieve a list of refund policies.
     *
     */
    public function testGetRefundPoliciesAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRefundPoliciesCountAsync
     *
     * Get the count of refund policies.
     *
     */
    public function testGetRefundPoliciesCountAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getRefundPolicyAsync
     *
     * Retrieve a refund policy by ID.
     *
     */
    public function testGetRefundPolicyAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getReturnPoliciesAsync
     *
     * Retrieve a list of return policies.
     *
     */
    public function testGetReturnPoliciesAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getReturnPoliciesCountAsync
     *
     * Get the count of return policies.
     *
     */
    public function testGetReturnPoliciesCountAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getReturnPolicyAsync
     *
     * Retrieve a return policy by ID.
     *
     */
    public function testGetReturnPolicyAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWarrantyPoliciesAsync
     *
     * Retrieve a list of warranty policies.
     *
     */
    public function testGetWarrantyPoliciesAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWarrantyPoliciesCountAsync
     *
     * Get the count of warranty policies.
     *
     */
    public function testGetWarrantyPoliciesCountAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getWarrantyPolicyAsync
     *
     * Retrieve a warranty policy by ID.
     *
     */
    public function testGetWarrantyPolicyAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateRefundPolicyAsync
     *
     * Update a refund policy.
     *
     */
    public function testUpdateRefundPolicyAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateReturnPolicyAsync
     *
     * Update a return policy.
     *
     */
    public function testUpdateReturnPolicyAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateWarrantyPolicyAsync
     *
     * Update a warranty policy.
     *
     */
    public function testUpdateWarrantyPolicyAsync()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
